# 1. Grant `cluster-monitoring-view` role to the `grafana-serviceaccount`
#  oc adm policy add-cluster-role-to-user cluster-monitoring-view -z grafana-serviceaccount
# 2. Get bearer token for `grafana-serviceaccount`. Update manifest.
#  oc serviceaccounts get-token grafana-serviceaccount -n thanos
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafana
  namespace: grafana-operator
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: prometheus
      secureJsonData:
        # Update bearer token to match your environment
        httpHeaderValue1: 'Bearer ${bearer}'
      type: prometheus
      url:  'https://thanos-querier-openshift-monitoring.apps.rosa.xuv78-3xtdb-xu7.pehe.p3.openshiftapps.com'
  name: prometheus-grafana.yaml
