---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  labels:
    app: sso
  name: jdoe
  namespace: keycloak-system
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    email: jdoe@redhat.com
    enabled: true
    firstName: Jane
    lastName: Doe
    username: jdoe
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  labels:
    app: sso
  name: somalley
  namespace: keycloak-system
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    email: somalley@redhat.com
    enabled: true
    firstName: Sally
    lastName: OMalley
    username: somalley
